spring.application.name=happiness-app
server.port=8080

# CORS 설정
server.servlet.context-path=/

# 기본 설정
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# H2 데이터베이스 설정
spring.datasource.url=jdbc:h2:mem:happinessdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 콘솔 활성화
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA 설정
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
